languageCode = "en"
languageName = "English"
title = "CoderDojo Poland Foundation"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Robisz coś dobrego – dla innych i dla siebie. Dołącz do ludzi, którzy chcą zmieniać świat technologią."
logo = "3D_przezroczyste.png"

  [params.author]
  name = "CoderDojo Poland"
  email = "dojo@coderdojo.org.pl"
  headline = "Empowering volunteers through coding education"
  bio = "CoderDojo Poland Foundation"
  links = [ ]